backend:
  name: git-gateway
  branch: main

# Configuration des médias
media_folder: "public/images/actualites"
public_folder: "/images/actualites"
media_library:
  name: uploadcare
  config:
    publicKey: "votre_cle_publique"

# Paramètres généraux du CMS
site_url: https://soakilonga.vercel.app
display_url: https://soakilonga.vercel.app
locale: "fr"

collections:
  - name: "actualites"
    label: "Actualités"
    folder: "content/actualites"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date de publication", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Contenu", name: "body", widget: "markdown" }
