backend:
  name: git-gateway
  branch: main

# Configuration des médias
media_folder: "public/images/actualites"
public_folder: "/images/actualites"

# Paramètres généraux du CMS
site_url: https://soakilonga.netlify.app
display_url: https://soakilonga.netlify.app
locale: "fr"

collections:
  - name: "actualites"
    label: "Actualités"
    folder: "content/actualites"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date de publication", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Contenu", name: "body", widget: "markdown" }

  - name: "team"
    label: "Équipe"
    folder: "content/team"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nom", name: "name", widget: "string" }
      - { label: "Rôle", name: "role", widget: "string" }
      - {
          label: "Centre",
          name: "center",
          widget: "select",
          options:
            [
              { label: "Fondateurs", value: "fondateurs" },
              { label: "Mahitsy", value: "mahitsy" },
              { label: "Tsarazaza", value: "tsarazaza" },
              { label: "Ihosy", value: "ihosy" },
            ],
        }
      - { label: "Photo", name: "photo", widget: "image" }
      - {
          label: "Ordre d'affichage",
          name: "order",
          widget: "number",
          value_type: "int",
          min: 1,
        }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: false,
        }
